// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTJMLk_CwcqW00PpstNXfdWSnc3pjM8a4',
    appId: '1:870746108398:web:ed9191cb27c94c5913deff',
    messagingSenderId: '870746108398',
    projectId: 'stuff-ride',
    authDomain: 'stuff-ride.firebaseapp.com',
    storageBucket: 'stuff-ride.firebasestorage.app',
    measurementId: 'G-9CKT2FR688',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHjjE5fNZVQgq8X6W7zynN0-xEn9h8KxQ',
    appId: '1:870746108398:android:2355c3098fffd61e13deff',
    messagingSenderId: '870746108398',
    projectId: 'stuff-ride',
    storageBucket: 'stuff-ride.firebasestorage.app',
  );
}
